name: Cloud Logging Settings
description: >-
  Settings for cloud logging, including locations for log storage, disabled _Default sinks, 
  and encryption keys.
scope: MEDIUM
privileges:
  get:
    risks: [discovery:logs]
  update:
    risks: [destruction:logs, impact:encryption]
    notes: >-
      Disabling the _Default log sink can cause loss of log entry data.
links:
  - https://cloud.google.com/logging/docs/access-control
  - https://cloud.google.com/logging/docs/default-settings
