name: Deploy catalog

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      project_number:
        required: true
        type: string
      project_id:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/${{ inputs.project_number }}/locations/global/workloadIdentityPools/${{ inputs.environment }}-id-pool/providers/${{ inputs.environment }}-gha-oidc-provider
          service_account: github-catalog-deploy-sa@${{ inputs.project_id }}.iam.gserviceaccount.com
          access_token_lifetime: 1200s
          create_credentials_file: true
      - uses: actions/setup-node@v3
        with:
          node-version: ^18.6.0
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: sudo apt install -y jq
      - run: yarn install
      - run: yarn ts-node scripts/generate.ts
      - run: >-
          cat dist/vulnerabilities.json | jq -c -r '.[]' > dist/vulnerabilities.jsonl && \
            cat dist/privileges.json | jq -c -r '.gcp[]' > dist/privileges-gcp.jsonl && \
            gcloud auth login --cred-file $GOOGLE_APPLICATION_CREDENTIALS && \
            bq load --project_id ${{ inputs.project_id }} --replace --source_format NEWLINE_DELIMITED_JSON --autodetect iam_risk.privileges-gcp dist/privileges-gcp.jsonl && \
            bq load --project_id ${{ inputs.project_id }} --replace --source_format NEWLINE_DELIMITED_JSON --autodetect iam_risk.vulnerabilities dist/vulnerabilities.jsonl
